### PR TITLE
Development - Add separators

### PR DESCRIPTION
**Pull request by lcfd**
https://github.com/noi-techpark/webcomp-meteo-generic/issues/18

### CODE REVIEW

**Comment by Piiit** [comment]
@lcfd Thx

**Comment by lcfd** [comment]
@Piiit let me know if is all right if so I'll implement it in the other components

**Comment by Piiit** [comment]
@lcfd I see that we have always only the title "Open Data Hub" in the search results, but below not all of them are from the ODH actually... Do you confirm?
Example: "antholz" shows many results, but only two are actually also a pin on the map called "Antholzersee" and "Antholz Obertal"... 

Another issue is, that when I click on a result the text disappears from the search, so that when I click something wrong I need to re-insert the search text. Google Maps for instance puts the text of the selection into the text field...

**Comment by lcfd** [comment]
@Piiit 

> Do you confirm?

Yes, I confirm. Also, mobility and ODH and all your data are the same for me (and for a normal user I guess), if you are talking about this. 

HereMaps is used only if open-data-hub doesn't return results. From #18 -> `That is, if the primary results from ODH are too long we can also omit the Here response.`

**Comment by Piiit** [comment]
> @Piiit
> 
> > Do you confirm?
> 
> Yes, I confirm. Also, mobility and ODH and all your data are the same for me (and for a normal user I guess), if you are talking about this.

What I am talking about is, that the pins on the map should be shown in the search list as primary result, if the others come from the ODH and are not related to weather they should not be shown in the search list as primary result. The widgets should have a focus on their domain. Hope that makes our request clearer... 

So for example, you could have the pins as primary results, and (if not too many results already), show other results below, but they should be distinguishable from the primary results, even if both are from the ODH.

> HereMaps is used only if open-data-hub doesn't return results. From #18 -> `That is, if the primary results from ODH are too long we can also omit the Here response.`

This is correct

**Comment by Piiit** [comment]
Maybe with an example all becomes clearer:

Search = "antholz"

List = 
```
OPEN DATA HUB
(pin) Antholzersee
(pin) Antholz Obertal
OTHER RESULTS
Lake Antholz
etc....
```

**Comment by Piiit** [comment]
So a "Antholz Ski Rental" has nothing to do with weather data from the ODH, and becomes part of "other results"...

**Comment by lcfd** [comment]
> if the others come from the ODH and are not related to weather they should not be shown in the search list as primary result

All the things that I show in the list, that are not data from heremaps API, are related to weather. Because that data are all meteo stations / misuration points related data.

---

```
OTHER RESULTS
Lake Antholz
etc....
```

It is already like that, try search with `nazionale` or `sanseverino`. You'll see the `HERE MAPS` section.

---

For `Antholz Ski Rental` I don't get data from any API, neither from here, nor from mobility, nor from tourism.

**Comment by Piiit** [comment]
So please could you explain me where these results are located on the map... I think there is something wrong here:
Selection_049

**Pull request merged**
